### PR TITLE
increasing limit amount for price

### PR DESCRIPTION
**Pull request by cvillalba**
The amount of money in prices for Chile can be greater for one more
decimal than the limit amount that is set right now

### CODE REVIEW

**Comment by cvillalba** [comment]
@etewiah Please check this change to increase the amount limit for prices.

Let my know if this would make it 

Cheers

**Comment by etewiah** [comment]
Thanks for this pull request @cvillalba.  With the compiled javascript files, it is better if I edit them myself so I will do that in the next code push I make tomorrow to fix the price limit.

**Comment by cvillalba** [comment]
@etewiah Ok, let me check the diff then I can learn a little more

Cheers

**Comment by cvillalba** [comment]
@etewiah could you change the limit on the amount, you can let me know if I can help you with anything about it.

**Comment by etewiah** [comment]
Hey @cvillalba, sorry I forgot to push the change out.  Just pushed it out a few hours ago.

I have also added functionlity to inject CSS directly into the website.  Hope you find it useful.  You can find it here:

https://propertywebbuilder.herokuapp.com/en/admin/website/settings/appearance

**Comment by cvillalba** [comment]
@etewiah  thank you very much.

Is it enough to update the gem in my project with `bundle update pwb` ?

**Comment by etewiah** [comment]
Yes, that should do the job.  If you encounter any issues just let me know.

**Pull request closed without merging**
